### ISSUE TITLE
Installing vmclarity in kubernetes "vmclarity-cr-discovery-server" image appears to be private

### ISSUE THREAD

**Issue by Starttoaster** [openclarity/vmclarity#1133]
## Description

I've been made to understand that kubeclarity was (from what I can tell) silently deprecated in favor of vmclarity. I'm installing it with mostly default values defined in this repo's helm chart, but changing the orchestrator provider config to "kubernetes". This causes a daemonset named "vmclarity-cr-discovery-server" to be installed, which utilizes an image tagged `ghcr.io/openclarity/vmclarity-cr-discovery-server:latest`. This image cannot be pulled, the event logging around which imply it exists but is a private image:

```
Failed to pull image "ghcr.io/openclarity/vmclarity-cr-discovery-server:latest": failed to pull and unpack image "ghcr.io/openclarity/vmclarity-cr-discovery-server:latest": failed to resolve reference "ghcr.io/openclarity/vmclarity-cr-discovery-server:latest": failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aopenclarity%2Fvmclarity-cr-discovery-server%3Apull&service=ghcr.io: 403 Forbidden
```

## Expected Behavior

Image pulled

## Actual Behavior

Image not pulled

## Affected Version

The trunk branch of this repo

## Steps to Reproduce

1. Install vmclarity in a cluster using your helm chart, changing the `openclarity.provider` option to "kubernetes" with no image pull secrets.
2. Observe your pods that won't start.

## Checklist

- [x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by Starttoaster** [comment]
Some documentation around configuring the kubernetes provider in https://openclarity.io/docs/vmclarity/getting-started/ would be most excellent as well, but is not directly related to this Issue. At best, maybe my Issue is a symptom of there not being documentation :)

I understand that the kubernetes provider for vmclarity is still in development though, so I might have raced to try things out before the official unveiling :(

**Comment by ramizpolic** [comment]
Hi @Starttoaster, we are currently working on consolidating Kubernetes support, along with Kubernetes scanning capabilities (defined in https://github.com/openclarity/vmclarity/issues/558).  The documentation is also being updated and k8s should be natively supported as a default option when installing the stack. Thanks for submitting this!
