### ISSUE TITLE
example in the configuration of running docker windows image

### ISSUE THREAD

**Issue by tomerse-sg** [openclarity/vmclarity#1577]
## Problem Statement
I want to run a simple example of docker windows image using the configuration (SBOM).

## Proposed Solution
add an example in the configuration / documentation how to run an SBOM scan to windows

**Comment by tomerse-sg** [comment]
hi, thanks for the answer!
I see the last release is v0.6.0, but windows support was merged later.
do you know when a release that includes windows will be published?

**Comment by lgecse** [comment]
hi @tomerse-sg , we just released the rc for v0.7.0 that containes windows support. Official release will be done not later than the 17th of May.

**Comment by tomerse-sg** [comment]
thanks for the answer!
is it planned to support also vulnerabilities?

**Comment by tomerse-sg** [comment]
another question - what distribution of windows does the tool supports? (sbom)
