### ISSUE TITLE
UI blank screen on refresh

### ISSUE THREAD

**Issue by ramizpolic** [openclarity/vmclarity#1669]
## Expected Behavior

Refresh just refreshes the page without loosing contents.

## Actual Behavior

When the UI is refreshed it turns into a blank screen.

## Affected Version

Please provide the version number where this issue was encountered.

## Steps to Reproduce

1. Start UI
1. Refresh UI page

## Checklist

- [x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by paralta** [comment]
https://github.com/openclarity/vmclarity/pull/1743
