### ISSUE TITLE
Windows vulnerability scanning

### ISSUE THREAD

**Issue by ramizpolic** [openclarity/vmclarity#1672]
## Overview

The SBOM analyzer for Windows works and can collect details about user- and system- applications and updates. We should be able to perform vulnerability scanning on Windows-generated SBOM. 

Windows vulnerability scanner can be implemented as a custom [scanner](https://github.com/openclarity/vmclarity/tree/main/plugins) plugin. Make sure to also add support for passing SBOM data from the Windows SBOM analyzer to the plugin.

**Comment by tomerse-sg** [comment]
can be very useful!
do you know if it is planned to be open source as well?

**Comment by ramizpolic** [comment]
Yup @tomerse-sg, all changes collected in our backlog tickets are changes that will be part of the open source codebase.

**Comment by ramizpolic** [comment]
Vulnerability support on Windows is supported by default through Trivy and Grype scanners. There is no need to perform vulnerability scanning on the VMClarity Windows-generated SBOM by our vulnerability scanners since these scanners generate internal SBOM anyway. 

Windows support in general can be tracked in https://github.com/openclarity/vmclarity/issues/1203

**Comment by tomerse-sg** [comment]
not sure it is accurate.
grype \ trivy doesn't know to find vulnerabilities for OS windows packages.. only .NET (in the open source version)

**Comment by ramizpolic** [comment]
will discuss this with the rest of the team on Monday and provide the details. thanks for addressing this @tomerse-sg

**Comment by tomerse-sg** [comment]
you can find some information on the challenge [here](https://claroty.com/team82/blog/from-kbs-to-cves-understanding-the-relationships-between-windows-security-updates-and-vulnerabilities)

**Comment by ramizpolic** [comment]
we have discussed this and decided not to continue with it as it would require adding new services to the stack and extensive changes to our SBOM analyzer. if it's something you would like to use, feel free to create or contribute by writing a custom Windows Vulnerability Plugin [scanner](https://github.com/openclarity/vmclarity/tree/main/plugins).
