### ISSUE TITLE
Support asset findings data on UI

### ISSUE THREAD

**Issue by ramizpolic** [openclarity/vmclarity#1766]
## Problem Statement

Following up the changes in the relationship between assets and findings https://github.com/openclarity/vmclarity/blob/main/rfc/change-asset-findings-relationships.md, UI changes are required in the Findings section. 

## Proposed Solution

![finding - findings](https://github.com/openclarity/vmclarity/assets/46568597/1171414d-894f-4b61-a0e3-cadfbc39b2ce)

In the Findings table, the `Asset Name`, `Asset Location` and `Found on` fields are deprecated. These fields should be replaced by the new fields `First seen` and `Last seen`.

![finding - finding details](https://github.com/openclarity/vmclarity/assets/46568597/b59af296-afb4-4079-b433-93b43f3c1d57)

In the Finding details page, the updates required reflect the updates in the Findings table page. Optionally, the `Last seen by` field which specifies the ID of the last Asset Scan that saw this particular finding can be added.

![finding - asset details](https://github.com/openclarity/vmclarity/assets/46568597/c8a168f6-7e4d-496a-ac40-463c951f3c70)

There is no longer have an 1:1 relationship between findings and assets, therefore this Asset details for a Finding page needs to be replaced by a table of Assets similar to the Assets table page. The assets in this table need to be filtered using the new Asset Findings Table by Finding ID.

Changes can be tested against the following branch: https://github.com/openclarity/vmclarity/pull/1758.

## Alternatives Considered

N/A

## Additional Context

N/A

**Comment by akijakya** [comment]
The idea of a `Last seen by` column has been ditched?

**Comment by paralta** [comment]
`Last seen by` is the asset scan ID which I believe is not visible in the UI (neither on the asset scans table page or on the asset scan details page), right? If that is the case, it would be better to hide that column.
