### ISSUE TITLE
[feature request] Support additional clouds through external k8s Cloud Provider implemenations

### ISSUE THREAD

**Issue by bugfest** [openclarity/vmclarity#261]
## Problem Statement
Support additional clouds (e.g.: Openstack) so that VMClarity can be deployed and integrated into other public or private clouds.

## Proposed Solution
Implement Cloud Provider model plugin so that cloud integrations are abstracted using exiting vendor-provided so that VMs/PVs volume snapshots can be scanned in such environments:
- https://github.com/topics/k8s-sig-cloud-provider
- https://github.com/topics/k8s-sig-storage

## Alternatives Considered
None

## Additional Context
N/A

**Comment by akpsgit** [comment]
Hi @bugfest, thanks a lot for opening the first issue :)

The ask is very high priority on our roadmap list. We will add the road map shortly.

The goal is to support AWS, Azure and GCP cloud providers at first phase. We plan to have these as built-in implementations of the provider client interface (runtime_scan/pkg/provider/client.go).
We also plan to have a gRPC implantation of the interface for the users to plug in (without code changes) their own custom provider integrations. We'll add a fake implementation of a gRPC provider as an example. 
Does that sound o.k, or maybe you have an additional suggestion?

Of course contributions of additional cloud provider integrations are more than welcome.

Thanks!
