### ISSUE TITLE
Move the family scanners logic into a separate repo (reuse of infra between kubeclarity and vmclarity)

### ISSUE THREAD

**Issue by akpsgit** [openclarity/vmclarity#346]
In order to untangle VMClarity and KubeClarity, improve maintainability, and make the OpenClarity multi-scanner CLI reusable we should move the CLI components to a separate repo and reorganise them.

The repo should be called "<TBD>" 

The components that should move from KubeClarity are:

* shared/pkg/job_manager
* shared/pkg/scanner
* shared/pkg/analyzer
* shared/pkg/converter
* shared/pkg/config
* shared/pkg/utils/cyclonedx_helper
* shared/pkg/utils/trivy
* shared/pkg/utils/image_helper
* shared/pkg/utils/sbom
* shared/pkg/utils/vulnerabiity
* shared/pkg/utils/input.go

The components that should move from VMClarity are:

* pkg/shared/families

The code once moved it should be reorganised to ensure that its a cohesive package, some examples are:

* the code in kubeclarity/pkg/analyzer should be moved into pkg/families/sbom and aligned with the other families
* the code in kubeclarity/pkg/scanner should be moved into pkg/families/vulnerabilities and aligned with the other families
* the code in shared/pkg/config/trivy.go should be split into pkg/families/sbom/trivy/config.go and pkg/families/vulnerabilties/trivy/config.go

After the move is performed the code that has been moved should be removed from KubeClarity and VMClarity, and the new repo should be used as a golang library to replace it.

Outside of this task some enhancements should be done to all the code that is now unified:

* Add context support all the way from the family manager to the scanners
* Refactor the job_manager to make it responsible for running the scanner in go routines, instead of the scanners themselves.

These should be opened and issues on the new repo.

**Comment by justaugustus** [comment]
cc: @edwarnicke

**Comment by lgecse** [comment]
@adamtagscherer @Tehsmash please add detailed description of what should be done here.

**Comment by ramizpolic** [comment]
The new destination repo https://github.com/openclarity/scanner-families has been created

**Comment by adamtagscherer** [comment]
The dependency between KubaClarity and VMClarity had been removed so this ticket can be closed.
