### ISSUE TITLE
YARA integration as a malware scanner

### ISSUE THREAD

**Issue by akpsgit** [openclarity/vmclarity#354]
> YARA is a tool aimed at (but not limited to) helping malware researchers to identify and classify malware samples.

YARA is a popular tool used by malware researchers and provides an extremely flexible way to search for malware across a file system. We should add YARA as a scanner in the malware family, it should follow a similar structure to the other scanners in VMClarity and we should also add a remote server to handle the YARA rule download and sync in a centralised way.

Subtasks:
- [x] #576

@pbalogh-sa  Can you please open some new issues and link them here as subtasks for this "epic". You can make sure Github links them together properly by adding them into the list in the format:
```
- [ ] #<issue number>
```

**Comment by lgecse** [comment]
#638 #576 is solving this.
