### ISSUE TITLE
Windows snapshots support

### ISSUE THREAD

**Issue by akpsgit** [openclarity/vmclarity#356]
Windows is a supported operating system on many of the public clouds, for example AWS and Azure both have support for Windows images. Today the VMClarity scanner is only capable of scanning Linux/Unix style volumes for issues. There are several reasons for this:

a) A number of the tools/scanners used by VMClarity only look for issues in Linux/Unix file locations
b) The VMClarity scanner will only find and mount common linux volume formats (ext4, ext3 etc) and not NTFS.

Operating system awareness (manual input / detected) should be added to the VMClarity scanning infrastructure such that scanners can decide:

a) if they are capable of scanning the provided input
b) if they need to do anything different to scan the target input

We should document what Operating Systems each scanner in all the families support so that users can create scan configurations which perform successfully if targeted at windows nodes.

We should look to see if there is at least one sbom and vulnerability scanner that supports a windows file system, and if there isn't we should add one to provide the minimum level of support for windows in VMClarity.

**Comment by ramizpolic** [comment]
Volume logic needs to be extended to support NTFS mounting/unmounting.

**Comment by ramizpolic** [comment]
Scanners are now able to scan Windows snapshots and windows-specific environments. Some of the scanners are not meant to be run against Windows, but this is outside of the scope of this issue and is captured in https://github.com/openclarity/vmclarity/issues/1203.
