### ISSUE TITLE
Property TargetIDs always null for /api/scans

### ISSUE THREAD

**Issue by mirac-cisco** [openclarity/vmclarity#361]
## Description

Call to `/api/scans` API always returns a null `targetIDs` for all returned `Scan` items.
`/api/scanResults` for the same scan correctly populates the `target.id` property.

## Expected Behavior

List of targets present in the output from `/api/scans`

## Actual Behavior

(see description)

## Affected Version
```
Version: latest
Commit: 3e45aa3bbd2689c6c12547943b6d1fa674307f88
```

## Steps to Reproduce

1. Have at least 1 scan finished
1. Call `<host>:<port>/api/scans` trough Postman or similar tool

## Checklist

- [x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by akpsgit** [comment]
Hi @mirac-cisco thanks for opening the issue. Looks like upon patch the targetIDs getting nullified. Need to change the lists in the API to be non nullable in order for patch not to nullify them. Thanks, we're on it.

**Comment by ramizpolic** [comment]
To be decided which part of milestone to put this in.

**Comment by akijakya** [comment]
We don't have `targetIDs` field and the `api/scanResults` endpoint anymore. The `api/scans` endpoint returns `assetIDs` now and returns the list correctly, so I'd assume this issue can be closed.
