### ISSUE TITLE
API /api/scanResults does not return targetInfo property

### ISSUE THREAD

**Issue by mirac-cisco** [openclarity/vmclarity#363]
## Description

Per OpenAPI specs [here](https://github.com/openclarity/vmclarity/blob/main/api/openapi.yaml#L1692), `target` property of `TargetScanResult` should contain `targetInfo` field ([ref](https://github.com/openclarity/vmclarity/blob/main/api/openapi.yaml#L1563)), but the property over 13 scan results and 3 scans does not exist, and only the id of the target is available.

I have tried passing the `?expand=True` and `?$expand=True`, but no change in behavior.

## Expected Behavior

Field is present.

## Actual Behavior

(see description)

## Affected Version

```
Version: latest
Commit: 3e45aa3bbd2689c6c12547943b6d1fa674307f88
```

## Steps to Reproduce

1. Have at least 1 scan finished
1. Call `<host>:<port>/api/scanResults` trough Postman or similar tool

## Checklist

- [x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by akpsgit** [comment]
Hi @mirac-cisco, the $expand filter is not a boolean like in you example. You should specify the field that you wish to expand. For example: 
curl -X 'GET'  "http://localhost:8080/api/scanResults?\$expand=target'" -H 'accept: application/json' | jq
For more details, please check:
https://www.odata.org/documentation/odata-version-2-0/uri-conventions/

**Comment by mirac-cisco** [comment]
Hi @akpsgit,

Thank you for the clarification. Note (because this is staying on the web) that there's a small typo in your answer, but once I removed the single quote after the word *target* it worked perfectly. Closing the issue with this.

**Comment by akpsgit** [comment]
> Hi @akpsgit,
> 
> Thank you for the clarification. Note (because this is staying on the web) that there's a small typo in your answer, but once I removed the single quote after the word _target_ it worked perfectly. Closing the issue with this.

Thanks, fixed :)
