### ISSUE TITLE
Dashboard - Riskiest asset is empty

### ISSUE THREAD

**Issue by FrimIdan** [openclarity/vmclarity#394]
## Description

Failed to get riskiest asset widget info from the backend.
The following error is shown in the logs.
```
Jun 11 14:46:52 ip-10-0-0-205 docker[8436]: time="2023-06-11T14:46:52Z" level=warning msg="Failed to get asset info, skipping target: failed to get asset type: unsupported provider: aws"
```

## Checklist

- [X] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [X] I have verified this does not duplicate an existing issue

**Comment by FrimIdan** [comment]
@chrisgacsal is there a reason why the vm info provider was not set with the AWS from the generated code?
```
InstanceProvider: utils.PointerTo(AWSProvider),
```
instead of
```
InstanceProvider: utils.PointerTo(models.AWS),
```

I think that both #391 is related following
```
	if *info.InstanceProvider == backendmodels.AWS {
		// AWS location is represented as region/vpc, need to return only the region
		return strings.Split(info.Location, "/")[0]
	}
```

**Comment by chrisgacsal** [comment]
@FrimIdan Nope, it's a bug. I'll fix it now.
