### ISSUE TITLE
Do not mark asset terminated if we found it but failed to patch

### ISSUE THREAD

**Issue by ghost** [openclarity/vmclarity#447]
Good point on marking it terminated if we fail to patch, perhaps I should skip the terminated processing if there are errors during the first part because we don't know if we've got completely accurate data?

_Originally posted by @sambetts-cisco in https://github.com/openclarity/vmclarity/pull/438#discussion_r1250969972_
            
Discovery happens in two phases:

* First phase calls the provider to list all the assets, and then creates/updates the assets in the VMClarity DB with a timestamp that indicates that it was discovered in this Discovery iteration.
* Second phase finds all the assets in the DB which don't have the timestamp from above, and then marks them as terminated.

If the first phase fails to patch an existing asset with the new timestamp, the second phase can mark the asset as terminated accidentally, therefore we should skip the second phase if the first phase fails.

**Comment by lgecse** [comment]
@paralta WDYT?
