### ISSUE TITLE
Unable to select scan types in scan configuration ui screen

### ISSUE THREAD

**Issue by FrimIdan** [openclarity/vmclarity#456]
## Description

Unable to select scan types in scan configuration ui screen
![image](https://github.com/openclarity/vmclarity/assets/40820488/0801acd2-0857-4f15-a4e5-1e3670cc7ab4)

## Affected Version

main

## Steps to Reproduce

Create new scan config

## Checklist

- [X] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [X] I have verified this does not duplicate an existing issue

**Comment by sambetts-cisco** [comment]
Fixed as part of https://github.com/openclarity/vmclarity/pull/466
