### ISSUE TITLE
Add Kubernetes release artifacts

### ISSUE THREAD

**Issue by ramizpolic** [openclarity/vmclarity#471]
Currently, we support AWS and Azure deployments. It would be beneficial to add Kubernetes deployments (preferably a Helm chart) for VMClarity.

**Comment by sambetts-cisco** [comment]
@ramizpolic thanks for adding this, the first step for this is #345 IMO, and thats something I'm going to be putting a PR up for soon. Once we've got that then I think a helm chart is 100% the right choice, and then we can think about EKS/AKS/GKE deployments.
