### ISSUE TITLE
Add Outshift Slack invite to the openclarity.io page

### ISSUE THREAD

**Issue by lgecse** [openclarity/vmclarity#511]
## Problem Statement

The OpenClarity community does not know where to get in touch with each other other than the GH. This will be needed so we could organize community meetings. 

## Proposed Solution

Add the Outshift Slack invite link to the openclarity.io page, I guess it should be like on https://bank-vaults.dev/ 

Come chat with us!
In case you need help, you can find us in our Slack channel.
[Join Slack …](https://join.slack.com/t/emergingtechcommunity/shared_invite/zt-1rw2jl0ht-yNdyFgBFlc~yzo9AnE4FbA)

## Alternatives Considered

N/A

## Additional Context

N/A

**Comment by dani-l-toth** [comment]
I cannot publish my local branch - being a member of the Openclarity organization is apparently not enough for that.

@lgecse could you please add me as a collaborator to the following repositories:
https://github.com/openclarity/openclarity.io
https://github.com/openclarity/apiclarity.io

**Comment by lgecse** [comment]
Done by @fekete-robert , closing.
