### ISSUE TITLE
Kubernetes Running Container Discovery

### ISSUE THREAD

**Issue by Tehsmash** [openclarity/vmclarity#562]
Following design #527, we should implement container discovery in the DiscoverAssets function added by #561.

The container discovery logic should fetch all pods from the cluster, scan for containerStatus' and return a new asset entry for each container which is not terminated:
- containerID this will be used as the "ID" field for the container asset.
- imageID this will be used to fill out the image part of the container asset using the digest not the tag.
- name this will be used to fill out the name part of the container asset

**Comment by FrimIdan** [comment]
@Tehsmash I would say we can also store the image tag (if found) for visibility

**Comment by Tehsmash** [comment]
Sounds like a good idea, I think we should extend the schema for ContainerImage to contain a list of known tags. Then if we find multiple tags for the same hash we can store them all.
