### ISSUE TITLE
Add ADOPTERS.md to VMClarity

### ISSUE THREAD

**Issue by lgecse** [openclarity/vmclarity#570]
Please add ADOPTERS.md file, so we could better track usage of the ~~APIClarity, KubeClarity and~~ VMClarity.

Example: bank-vaults, logging-operator

**Comment by lgecse** [comment]
@paralta I'll create a separate item for the APIClarity and KubeClarity.

**Comment by lgecse** [comment]
Please refer the file in the README.md as well.

**Comment by paralta** [comment]
Marking as `won't fix` as this issue will not be addressed for now.
