### ISSUE TITLE
Add pinned message to Slack for the adopters

### ISSUE THREAD

**Issue by lgecse** [openclarity/vmclarity#571]
On the Outshift Slack instance we need a pinned message that asks users to add themselves as adopters to the ADOPTERS.md created in #570

**Comment by lgecse** [comment]
Example from #bank-vaults: 

> We have added an Adopters list to the repository, feel free to add your use-case, workload description, etc. in a PR, this list means a lot to us! :slightly_smiling_face: Thanks
>https://github.com/banzaicloud/bank-vaults/blob/master/ADOPTERS.md

**Comment by paralta** [comment]
Marking as `won't fix` as this issue will not be addressed for now.
