### ISSUE TITLE
gitleaks scanner is failing to scan large files

### ISSUE THREAD

**Issue by fishkerez** [openclarity/vmclarity#622]
## Description

Scanner family: Secrets
Scanner: gitleaks
Provider: AWS
Root volume size: 30 GB
Actual size (from stats): 30 GB (volume is full)

Error from gitleaks scanner:
`
failed to scan input "/mnt/snapshots/70f9ca4f-04b6-4fef-ba6e-d439f65e605f" for secrets: 1 error occurred: * "gitleaks" job failed: failed to run gitleaks command: failed to run command /artifacts/gitleaks detect --source=/mnt/snapshots/70f9ca4f-04b6-4fef-ba6e-d439f65e605f --no-git -r /tmp/gitleaks265272964 -f json --exit-code 0, error: exit status 2, stdout: , stderr: ○ │╲ │ ○ ○ ░ ░ gitleaks fatal error: runtime: out of memory runtime stack: runtime.throw({0x7b929d?, 0x50ac00000?}) /usr/local/go/src/runtime/panic.go:992 +0x71 runtime.sysMap(0xc022400000, 0xc00003fe90?, 0xc00003fef8?) /usr/local/go/src/runtime/mem_linux.go:189 +0x11b runtime.(*mheap).grow(0xa872a0, 0x2855d0?) /usr/local/go/src/runtime/mheap.go:1404 +0x225 runtime.(*mheap).allocSpan(0xa872a0, 0x2855d0, 0x0, 0x1) /usr/local/go/src/runtime/mheap.go:1170 +0x171 runtime.(*mheap).alloc.func1() /usr/local/go/src/runtime/mheap.go:912 +0x65 runtime.systemstack() /usr/local/go/src/runtime/asm_amd64.s:469 +0x49 goroutine 1389 [running]: runtime.systemstack_switch() /usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc00068d9c8 sp=0xc00068d9c0 pc=0x460d80 runtime.(*mheap).alloc(0x50aba0000?, 0x2855d0?, 0x3?) /usr/local/go/src/runtime/mheap.go:906 +0x65 fp=0xc00068da10 sp=0xc00068d9c8 pc=0x426445 runtime.(*mcache).allocLarge(0x49a5d1?, 0x50ab9e001, 0x1) /usr/local/go/src/runtime/mcache.go:213 +0x85 fp=0xc00068da60 sp=0xc00068da10 pc=0x416945 runtime.mallocgc(0x50ab9e001, 0x74b5c0, 0x1) /usr/local/go/src/runtime/malloc.go:1096 +0x5a5 fp=0xc00068dad8 sp=0xc00068da60 pc=0x40d1e5 runtime.makeslice(0xc001f34378?, 0x55?, 0x0?) /usr/local/go/src/runtime/slice.go:103 +0x52 fp=0xc00068db00 sp=0xc00068dad8 pc=0x44a3b2 os.ReadFile({0xc001f22e40?, 0x55?}) /usr/local/go/src/os/file.go:693 +0xeb fp=0xc00068dbe0 sp=0xc00068db00 pc=0x4a1d0b github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectFiles.func2() /Users/zrice/code/zricethezav/gitleaks/detect/detect.go:445 +0x6a fp=0xc00068df38 sp=0xc00068dbe0 pc=0x71cdaa github.com/fatih/semgroup.(*Group).Go.func1() /Users/zrice/Go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0xa2 fp=0xc00068dfe0 sp=0xc00068df38 pc=0x6e8222 runtime.goexit() /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00068dfe8 sp=0xc00068dfe0 pc=0x462e61 created by github.com/fatih/semgroup.(*Group).Go /Users/zrice/Go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x23e goroutine 1 [select]: golang.org/x/sync/semaphore.(*Weighted).Acquire(0xc00005a0f0, {0x84c728, 0xc00009c000}, 0x1) /Users/zrice/Go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/semaphore/semaphore.go:60 +0x345 github.com/fatih/semgroup.(*Group).Go(0xc00005a140, 0xc001f542d0) /Users/zrice/Go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:51 +0x6e github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectFiles(0xc000110300, {0x7ffc72437f14, 0x33}) /Users/zrice/code/zricethezav/gitleaks/detect/detect.go:444 +0x170 github.com/zricethezav/gitleaks/v8/cmd.runDetect(0xa62b00?, {0x7b1798?, 0x8?, 0x8?}) /Users/zrice/code/zricethezav/gitleaks/cmd/detect.go:120 +0xac5 github.com/spf13/cobra.(*Command).execute(0xa62b00, {0xc00010c400, 0x8, 0x8}) /Users/zrice/Go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x663 github.com/spf13/cobra.(*Command).ExecuteC(0xa62880) /Users/zrice/Go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4 github.com/spf13/cobra.(*Command).Execute(...) /Users/zrice/Go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902 github.com/zricethezav/gitleaks/v8/cmd.Execute() /Users/zrice/code/zricethezav/gitleaks/cmd/root.go:141 +0x25 main.main() /Users/zrice/code/zricethezav/gitleaks/main.go:22 +0x211 goroutine 19 [syscall]: os/signal.signal_recv() /usr/local/go/src/runtime/sigqueue.go:151 +0x2f os/signal.loop() /usr/local/go/src/os/signal/signal_unix.go:23 +0x19 created by os/signal.Notify.func1.1 /usr/local/go/src/os/signal/signal.go:151 +0x2a goroutine 20 [chan receive]: main.listenForInterrupt(0x0?) /Users/zrice/code/zricethezav/gitleaks/main.go:26 +0x1b created by main.main /Users/zrice/code/zricethezav/gitleaks/main.go:20 +0x20c goroutine 6 [chan send]: github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectFiles.func1.1({0xc001f23200, 0x5a}, {0x84cdf8, 0xc001f531e0}, {0x0?, 0x0?}) /Users/zrice/code/zricethezav/gitleaks/detect/detect.go:419 +0x15a path/filepath.walk({0xc001f23200, 0x5a}, {0x84cdf8, 0xc001f531e0}, 0xc000892f08) /usr/local/go/src/path/filepath/path.go:418 +0x123 path/filepath.walk({0xc001e072c0, 0x49}, {0x84cdf8, 0xc001f52f70}, 0xc000892f08) /usr/local/go/src/path/filepath/path.go:442 +0x285 path/filepath.walk({0xc001e071d0, 0x47}, {0x84cdf8, 0xc001f52ea0}, 0xc000892f08) /usr/local/go/src/path/filepath/path.go:442 +0x285 path/filepath.walk({0xc001e070e0, 0x44}, {0x84cdf8, 0xc001f52dd0}, 0xc000892f08) /usr/local/go/src/path/filepath/path.go:442 +0x285 path/filepath.walk({0xc001cf0c00, 0x37}, {0x84cdf8, 0xc001f52820}, 0xc000892f08) /usr/local/go/src/path/filepath/path.go:442 +0x285 path/filepath.walk({0x7ffc72437f14, 0x33}, {0x84cdf8, 0xc00008e5b0}, 0xc000892f08) /usr/local/go/src/path/filepath/path.go:442 +0x285 path/filepath.Walk({0x7ffc72437f14, 0x33}, 0xc00088df08) /usr/local/go/src/path/filepath/path.go:505 +0x6c github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectFiles.func1() /Users/zrice/code/zricethezav/gitleaks/detect/detect.go:407 +0x94 github.com/fatih/semgroup.(*Group).Go.func1() /Users/zrice/Go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0xa2 created by github.com/fatih/semgroup.(*Group).Go /Users/zrice/Go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x23e goroutine 10 [runnable]: regexp.(*machine).match(0xc0010ba000, {0x84cbb0, 0xc0010ba0c0}, 0x0) /usr/local/go/src/regexp/exec.go:225 +0x3e0 regexp.(*Regexp).doExecute(0xc000011c20, {0x0?, 0x0}, {0x0, 0x0, 0x0}, {0xc012e3c000, 0x25e3732}, 0x155?, 0x4, ...) /usr/local/go/src/regexp/exec.go:542 +0x319 regexp.(*Regexp).allMatches(0xc000011c20, {0xc012e3c000, 0x25e3732}, {0x0, 0x0, 0x0}, 0x25e3733, 0xc00090f4d0) /usr/local/go/src/regexp/regexp.go:782 +0x131 regexp.(*Regexp).FindAllStringIndex(0xc000afb8c0?, {0xc012e3c000?, 0x0?}, 0x0?) /usr/local/go/src/regexp/regexp.go:1139 +0x66 github.com/zricethezav/gitleaks/v8/detect.(*Detector).detectRule(_, {{0xc012e3c000, 0x25e3732}, {0xc000afb8c0, 0x52}, {0x0, 0x0}, {0x0, 0x0}, {0xc015420000, ...}, ...}, ...) /Users/zrice/code/zricethezav/gitleaks/detect/detect.go:233 +0x4d9 github.com/zricethezav/gitleaks/v8/detect.(*Detector).Detect(0xc000110300, {{0xc012e3c000, 0x25e3732}, {0xc000afb8c0, 0x52}, {0x0, 0x0}, {0x0, 0x0}, {0xc015420000, ...}, ...}) /Users/zrice/code/zricethezav/gitleaks/detect/detect.go:551 +0x585 github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectFiles.func2() /Users/zrice/code/zricethezav/gitleaks/detect/detect.go:465 +0x22a github.com/fatih/semgroup.(*Group).Go.func1() /Users/zrice/Go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0xa2 created by github.com/fatih/semgroup.(*Group).Go /Users/zrice/Go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x23e goroutine 594 [runnable]: unicode.SimpleFold(0x41?) /usr/local/go/src/unicode/letter.go:338 +0x11a regexp/syntax.(*Inst).MatchRunePos(0xc0008a7228?, 0x2c) /usr/local/go/src/regexp/syntax/prog.go:216 +0x76 regexp/syntax.(*Inst).MatchRune(...) /usr/local/go/src/regexp/syntax/prog.go:194 regexp.(*machine).step(0xc0008ac3c0, 0xc0008ac400, 0xc0008ac3d0?, 0xe2daa8, 0xc0001f4260?, 0x2c, 0x4?) /usr/local/go/src/regexp/exec.go:295 +0x35e regexp.(*machine).match(0xc0008ac3c0, {0x84cbb0, 0xc0008ac480}, 0x0) /usr/local/go/src/regexp/exec.go:225 +0x437 regexp.(*Regexp).doExecute(0xc0001ce5a0, {0x0?, 0x0}, {0x0, 0x0, 0x0}, {0xc00942c000, 0x2683df1}, 0x0?, 0x4, ...) /usr/local/go/src/regexp/exec.go:542 +0x319 regexp.(*Regexp).allMatches(0xc0001ce5a0, {0xc00942c000, 0x2683df1}, {0x0, 0x0, 0x0}, 0x2683df2, 0xc0008a74d0) /usr/local/go/src/regexp/regexp.go:782 +0x131 regexp.(*Regexp).FindAllStringIndex(0xc000afb740?, {0xc00942c000?, 0xc00000e1b8?}, 0x1?) /usr/local/go/src/regexp/regexp.go:1139 +0x66 github.com/zricethezav/gitleaks/v8/detect.(*Detector).detectRule(_, {{0xc00942c000, 0x2683df1}, {0xc000afb740, 0x53}, {0x0, 0x0}, {0x0, 0x0}, {0xc003e20000, ...}, ...}, ...) /Users/zrice/code/zricethezav/gitleaks/detect/detect.go:233 +0x4d9 github.com/zricethezav/gitleaks/v8/detect.(*Detector).Detect(0xc000110300, {{0xc00942c000, 0x2683df1}, {0xc000afb740, 0x53}, {0x0, 0x0}, {0x0, 0x0}, {0xc003e20000, ...}, ...}) /Users/zrice/code/zricethezav/gitleaks/detect/detect.go:551 +0x585 github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectFiles.func2() /Users/zrice/code/zricethezav/gitleaks/detect/detect.go:465 +0x22a github.com/fatih/semgroup.(*Group).Go.func1() /Users/zrice/Go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0xa2 created by github.com/fatih/semgroup.(*Group).Go /Users/zrice/Go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x23e
`

## Expected Behavior

gitleaks is able to scan and not using any memory on the scanned machine disk

## Actual Behavior

gitleaks is failing to scan due to OOM

## Affected Version

VMClarity tag: v0.5.0

## Steps to Reproduce

Scan an instance which has a very large file, with Secrets family enabled.

## Checklist

- [* ] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ *] I have verified this does not duplicate an existing issue

**Comment by akpsgit** [comment]
Looks like OOM happened here:
https://github.com/gitleaks/gitleaks/blob/v8.15.1/detect/detect.go#L445
upon ```b, err := os.ReadFile(p.Path)```
Doesn't look like there is a file size limit filter in the FS walk logic, so it can easily crash on OOM.
looks like need to set ```--max-target-megabytes int   files larger than this will be skipped```
https://github.com/gitleaks/gitleaks/blob/ed34259e9c28b753c4017efe1d56a6623346abd0/README.md?plain=1#L156
