### ISSUE TITLE
Add possibility to use raw yara rule sources.

### ISSUE THREAD

**Issue by pbalogh-sa** [openclarity/vmclarity#678]
## Problem Statement

I think we should have two options for Rule sources:

CompiledRuleURL - a URL (file://, http:// or https://) which points to a compiled set of yara rules
RuleSources - the rule sources for raw yara rules. 

## Proposed Solution

RuleSources - a structure identical to the yara rule server configuration sources. We can then use the yara-server code as a library to download and index those sources prior to running yara.

**Comment by paralta** [comment]
Already supported
