### ISSUE TITLE
Nil pointer error if ContainerImageInfo.ID is not set

### ISSUE THREAD

**Issue by Tehsmash** [openclarity/vmclarity#707]
## Description

API Server returns a 500 Internal Server error if the ContainerImageInfo.Id field is not set. This is caused by a nil pointer panic when the checkUniqueness function tries to deference it. 

## Expected Behavior

If ID is a required field, the code should check this and return a 400 bad request error. 

## Actual Behavior

API Server returns a 500 Internal Server error if the ContainerImageInfo.Id field is not set.

## Affected Version

main

## Steps to Reproduce

POST an asset with ContainerImageInfo.ID not set.

## Checklist

- [X] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [X] I have verified this does not duplicate an existing issue

**Comment by Mihai22125** [comment]
Hello! I'd like to work on this item. Could you assign it to me, please?
