### ISSUE TITLE
Documentation: Add K8s onboarding as the first option 

### ISSUE THREAD

**Issue by akpsgit** [openclarity/vmclarity#811]
Once the helm chart is published (#808) , need to add the relevant K8s onboarding steps as the first option in https://github.com/openclarity/vmclarity#quick-start

**Comment by paralta** [comment]
https://openclarity.io/docs/vmclarity/getting-started/deploy-kubernetes/ Kubernetes deployment guide added to new documentation. Please note that we no longer maintain the getting started documentation in the README file.
