### ISSUE TITLE
Remove KubeClarity as a package dependency

### ISSUE THREAD

**Issue by ramizpolic** [openclarity/vmclarity#993]
We want to remove KubeClarity as a package dependency due to project migration.

Issues:
- #642 
- #643 (not needed for now, we can use the new repo as an import package)
- Remove leftover usage of `github.com/openclarity/kubeclarity` packages

**Comment by paralta** [comment]
The agreed approach to remove KubeClarity as a package dependency is to move all the required code to VMClarity. This will be the scope of this issue.

A follow up issue will be to move the family scanners logic into a separate repository https://github.com/openclarity/vmclarity/issues/346.
